---
    - name: "install telegraf"
      yum:
        name: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
        state: present
    - name: "copy cfg into dest"
      template:
        src: templates/telegraf.conf
        dest: /etc/telegraf/telegraf.conf
    - name: "start telegraf"
      service:
        name: "telegraf"
        state: restarted