---
- hosts: nginx_nodes
  become: yes
  vars:
    app_ips: 
      - privateIP
      - privateIP
    domain: fakeDomain.tk
    mail: fakeMail@mail.com
  tasks:
    - include_tasks: tasks/install-nginx.yml

- hosts: application_nodes
  become: yes
  vars:
    # app_location: /opt/carrental/carrental.jar
    # app_user: carrent
    metric_store_ip: privateIP
  tasks:
    # - include_tasks: tasks/install-car_rental.yml
    - include_tasks: tasks/install-marvel_base.yml
    - include_tasks: tasks/metrics/install-telegraf.yml
    
- hosts: metrics_nodes
  become: yes
  vars:
    grafana_ip: publicIP
    metric_store_ip: privateIP
  tasks:
    - include_tasks: tasks/metrics/install-influxdb.yml
    - include_tasks: tasks/metrics/install-grafana.yml

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    