---
- hosts: nginx_nodes
  become: yes
  vars:
    app_ips: 
      - 172.31.27.80
      - 172.31.25.176
    domain: adsk-199329.tk
  tasks:
    - include_tasks: tasks/install-nginx.yml

- hosts: application_nodes
  become: yes
  vars:
    app_location: /opt/carrental/carrental.jar
    app_user: carrent
    metric_store_ip: 172.31.18.19
  tasks:
    # - include_tasks: tasks/install-car_rental.yml
    - include_tasks: tasks/install-marvel_base.yml
    - include_tasks: tasks/metrics/install-telegraf.yml
    
- hosts: metrics_nodes
  become: yes
  vars:
    grafana_ip: 35.159.51.64
    metric_store_ip: 172.31.18.19
  tasks:
    - include_tasks: tasks/metrics/install-influxdb.yml
    - include_tasks: tasks/metrics/install-grafana.yml

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    