---
    - name: "install jre"
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: "create path"
      file:
        path: /opt/carrental
        state: directory
    - name: "copy .jar to remote machine"
      copy:
        src: car_rental/car_rental.jar
        dest: "{{app_location}}"
    - name: "create user for service"
      user:
        name: "{{app_user}}"
    - name: "copy systemd config"
      template:
        src: car_rental/car_rental.service
        dest: /etc/systemd/system/car_rental.service
    - name: "start service"
      systemd:
        name: "car_rental"
        daemon_reload: yes
        state: restarted