---
    - name: "Install EPEL"
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: "Install nginx"
      yum:
        name: nginx
        state: present    
    - name: "Copy cfg into dest"
      template:
        src: templates/nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: "Start nginx"
      service:
        name: "nginx"
        state: restarted
    - yum:
        name: python2-certbot-nginx
        state: present
    - shell: sudo certbot -i nginx -n -d "{{domain}}" --nginx -m "{{mail}}" --agree-tos --redirect